common_args:
  period: 1440
  dataset_name: aiops2018

experiments:
  kontrast:
    - omega: 240
      mode: 'P'
      K: 5
      dataset_size: 40000
      epoch: 500
      batch_size: 2000
      lstm_hidden_dim: 256
      lstm_output_dim: 256
      lr: 0.00005